name: CI-common-web

on:
  pull_request:
    types: [ready_for_review, opened, synchronize, reopened]
    branches: [ main ]
    paths:
      - 'packages/common-web/**'
  workflow_dispatch:

jobs:
  lint-build-test:
    if: github.event.pull_request.draft != true
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/common-web

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install packages
        run: yarn

      - name: Build
        run: yarn build

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test
