name: CI-common-web

on:
  pull_request:
    types: [ready_for_review, opened, synchronize, reopened]
    branches: [ main ]
    paths:
      - 'packages/common-web/**'
  workflow_dispatch:

jobs:
  lint-build-test:
    if: github.event.pull_request.draft != true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install packages
        run: npm i

      - name: Build
        working-directory: ./packages/common-web
        run: npm run build

      - name: Lint
        working-directory: ./packages/common-web
        run: npm run lint

      - name: Test
        working-directory: ./packages/common-web
        run: npm run test
